IF OBJECT_ID('spSalvarExecucao') IS NOT NULL
	DROP PROCEDURE spSalvarExecucao
GO
CREATE PROCEDURE spSalvarExecucao (
	@IDAGENDAMENTO INT,
	@IDCOMANDO INT,
	@DATA DATETIME,
	@HORARIO DATETIME,
	@EXECUTADO BIT,
	@CADASTRADOEM DATETIME,
	@ATUALIZADOEM DATETIME
)
AS
	BEGIN
		
		INSERT INTO 
		Execucao 
		(
			AgendamentoId,
			ComandoId,
			Data,
			Horario,
			Executado,
			CadastradoEm,
			AtualizadoEm
		)
		VALUES
		(
			@IDAGENDAMENTO,
			@IDCOMANDO,
			@DATA,
			@HORARIO,
			@EXECUTADO,
			@CADASTRADOEM,
			@ATUALIZADOEM
		)

		SELECT SCOPE_IDENTITY();

	END